//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mrucznik
{
    using System;
    using System.Collections.Generic;
    
    public partial class mru_konta
    {
        public long id { get; set; }
        public string pass { get; set; }
    }
}
